### PR TITLE
Merged forked release 2.8.0 (a2R1T000002QTyrUAG)

### PR DESCRIPTION
**Pull request by gorazd-up2go**
lwc test should run: execute npm test

apex test should run

### CODE REVIEW

**Comment by gorazd-up2go** [comment]
@rajas94 I put you as reviewer as you created "additional feature".

**Review by itsmebasti — APPROVED** [review]
nice, looks good.
I also compared it to main and saw that you could even improve or revert some things 👍 
Interesting that they also stumbled over the regexp, maybe we should have contributed some changes..

**Review by rajas94 — APPROVED** [review]
looks good

**Comment by gorazd-up2go** [comment]
I merged it locally and pushed through local git.

**Pull request closed without merging**
